DEVICE_PATH := device/Symphony/Symphony_Z50

# For building with TWRP minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# Architecture (arm64)
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

# Assert
TARGET_OTA_ASSERT_DEVICE := Symphony_Z50

# File systems
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Kernel
BOARD_KERNEL_CMDLINE :=BOARD_KERNEL_CMDLINE bootopt=64S3,32N2,64N2 androidboot.selinux=permissive buildvariant=eng
BOARD_KERNEL_BASE 0x40078000
BOARD_NAME 
BOARD_PAGE_SIZE 2048
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x11f88000
BOARD_SECOND_OFFSET 0x00e88000
BOARD_TAGS_OFFSET 0x12f88000
BOARD_OS_VERSION 11.0.0
BOARD_OS_PATCH_LEVEL 2025-12
BOARD_HEADER_VERSION 2
BOARD_RECOVERY_DTBO_SIZE 46594
BOARD_RECOVERY_DTBO_OFFSET 24940544
BOARD_HEADER_SIZE 1660
BOARD_DTB_SIZE 108612
BOARD_DTB_OFFSET 0x12f88000
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/zImage
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x11f88000
BOARD_KERNEL_TAGS_OFFSET := 0x12f88000
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)

# Platform
TARGET_BOARD_PLATFORM := mt6757

# Hack: prevent anti rollback
PLATFORM_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 16.1.0

# TWRP 
# Version := 1.0.1
TW_DEVICE_VERSION := 1
TW_THEME := portrait_hdpi
TARGET_SCREEN_WIDTH := 720
TARGET_SCREEN_HEIGHT := 1560
RECOVERY_SDCARD_ON_DATA := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 93
TW_INCLUDE_NTFS_3G := true
TW_USE_NEW_MINADBD := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_EXTRA_LANGUAGES := true
TARGET_USES_MKE2FS := true
TW_NO_LEGACY_PROPS := true
TW_NO_BIND_SYSTEM := true
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true

TW_Y_OFFSET := 60
TW_H_OFFSET := -60

# SHRP
SHRP_DEVICE_CODE := Symphony_Z50
SHRP_PATH := device/Symphony/$(SHRP_DEVICE_CODE)
SHRP_MAINTAINER := Symphony
SHRP_REC_TYPE := Normal
SHRP_DEVICE_TYPE := A_Only
SHRP_REC := /dev/block/platform/bootdevice/by-name/recovery
SHRP_INTERNAL := /sdcard
SHRP_EXTERNAL := /external_sd
SHRP_OTG := /usb_otg

SHRP_STATUSBAR_RIGHT_PADDING := 20
SHRP_STATUSBAR_LEFT_PADDING := 20
SHRP_NOTCH := true
SHRP_EXPRESS := true
SHRP_LITE := true

# LEDS INFO
# "/sys/class/leds/blue/brightness" - Blue LED - Max - 6
# "/sys/class/leds/green/brightness" - Green LED - Max - 6
# "/sys/class/leds/red/brightness" - Red LED - Max -





